name: green_cycle
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.2
  dio: ^5.3.2
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  flutter_smart_dialog: ^4.9.4
  flutter_spinkit: ^5.2.0
  flutter_svg: ^2.0.7
  form_builder_validators: ^9.0.0
  get: ^4.6.5
  get_storage: ^2.1.1
  intl: ^0.18.1
  pin_code_fields: ^8.0.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Montserrat-Arabic
      fonts:
        - asset: assets/fonts/Montserrat-Arabic900.otf
        - weight: 900
        - asset: assets/fonts/Montserrat-Arabic800.otf
        - weight: 800
        - asset: assets/fonts/Montserrat-Arabic700.otf
        - weight: 700
        - asset: assets/fonts/Montserrat-Arabic600.otf
        - weight: 600
        - asset: assets/fonts/Montserrat-Arabic500.otf
        - weight: 500
        - asset: assets/fonts/Montserrat-Arabic400.otf
        - weight: 400
        - asset: assets/fonts/Montserrat-Arabic300.otf
        - weight: 300
        - asset: assets/fonts/Montserrat-Arabic250.otf
        - weight: 200
